### ISSUE TITLE
Human friendly error messages

### ISSUE THREAD

**Issue by flavio** [roscheer/fuse4redis#2]
Right now the majority of redis errors messages are not really "human friendly". They just return the type of the reply. Isn't there a way to improve the situation?

**Comment by roscheer** [comment]
I assume the messages referred here are the errors written to the log file. That file was originally meant for debugging only. The lack of friendliness is a real issue, and the error messages also lack precision/resolution, since all unexpected responses (different from the "happy path") are usually treated as the same error. I will make the log more useful for administrative purposes and post it here by tomorrow.

**Comment by roscheer** [comment]
Redis provides descriptive text messages in a return structure. These messages are now being logged along with the error codes. This fix was made simpler due to the fact that most of the errors are now handled in the function that wraps the redisCommand hiredis API call (issue #1 fix).

Additionally there are two additional error conditions that can occur:
a) Redis answers with a reply type indicating an error: these could only be generated, on the testing performed, by issuing a malformed command to redis. This should not happen at run time unless there is an error in the code. Anyway the descriptive error message redis returns is now being logged.
b) Redis replies with a response type other than the one that would be reasonably expected for the command issued (e.g it replies with a type indicating a string response when you'd expect an integer). This is also a coding error and should not happen normally. These occurrences are also all being logged.

All these critical error messages now have the "ERROR" string embedded, since the log still contains a lot of messages that are mostly debugging info.  The debugging messages should become eventually removed, or enabled through some configuration parameter only.
